export const defaultTheme = {
  colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForBackground: "#d8ecfe;",
  colorForGoodFeature: "#e1eddce;",
  colorForNegativeFeature: "#f8ddd7",
  colorForGoodOwner: "#88aa4d",
  colorforBadOwnwer: "#f75531",
  colorForButton: "#fc9b27",
  colorForButtonHover: "#fc7427",
  pagePadding: "90px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  lineHeightDefault: 1.5,
  headerHeight: "80px",
  footerHeight: "80px",
  pageWidth: "1280px",
  indent: "20px"
};
